OPENAI_API_KEY="sk-proj-r74hMDdRzTcFVsMQcVHIT3BlbkFJUxpUlQ5dgYNNA6H7B7iW"
GROQ_API_KEY="" # optional
SNOWFLAKE_ACCOUNT="ucxdzsd-fr16994"
SNOWFLAKE_USER="snehilaryan3298"
SNOWFLAKE_PASSWORD="Breakingbad1"
SNOWFLAKE_ROLE="ACCOUNTADMIN"
SNOWFLAKE_DATABASE="SNOWFLAKE_SAMPLE_DATA"
SNOWFLAKE_SCHEMA="TPCDS_SF10TCL"
SNOWFLAKE_WAREHOUSE="COMPUTE_WH"