OPENAI_API_KEY = "sk-proj-PEDWbGTMIIIu3e49VrTGT3BlbkFJ695El2p9OX8OucEaThS7"

[connections.snowflake]
user = "DEVESH123"
password = "Devesh1234"
warehouse = "HOL_WH"
role = "ACCOUNTADMIN"
# Find your account info here:
# https://docs.snowflake.com/en/user-guide/admin-account-identifier
account = "mashkgd-pe10017"
